Fb365
spiretrading/pyaugur pull request #3
Opened 2018-12-10 18:07 UTC by joelaro04

2018-12-10 18:28 UTC, kranar requested changes
Much much better.

2018-12-10 18:28 UTC, kranar commented on augur/augur_client.py
> +    self._is_open = False
You will need to perform an actual disconnection here.

2018-12-10 18:28 UTC, kranar commented on augur/augur_client.py
> +    s1 = re.sub('(.)([A-Z][a-z]+)', r'\1_\2', text)
Make this an internal free function rather than a method.

2018-12-10 18:28 UTC, kranar commented on augur/augur_client.py
> +    try:
Make this an internal free function instead of a method. In general any functions that do not depend on ```self``` should be free functions. Internal functions are prefixed with an underscore.

2018-12-10 18:42 UTC, joelaro04 commented on augur/augur_client.py
> +    s1 = re.sub('(.)([A-Z][a-z]+)', r'\1_\2', text)
I realize this function doesn't get used in the current implementation. I'll remove this for now.

2019-01-17 17:31 UTC, kranar approved these changes

2019-01-17 17:31 UTC, merged